
management:
  metrics:
    web:
      server:
        autoTimeRequests: false
server:
  port: 9000
zipkin:
  storage:
    type: elasticsearch #存储类型或者Elk
    elasticsearch:
      cluster: elasticsearch
      hosts: http://localhost:9200
      index: zipkin